### PR TITLE
Fix health checks

### PR DESCRIPTION
**Pull request by tammert**
* `wget -s` isn't a valid option
* mailcatcher doesn't have `curl` installed

### CODE REVIEW

**Comment by tammert** [comment]
Fixes #18

**Comment by olger** [comment]
Hi @tammert 

When I startup, there are still some issues:

` docker-compose ps                        ✔  10256  14:17:44
   Name                  Command                   State                                             Ports
------------------------------------------------------------------------------------------------------------------------------------------------
cafienne      /opt/cafienne/bin/case-service   Up (unhealthy)   0.0.0.0:2027->2027/tcp,:::2027->2027/tcp, 9999/tcp
generic-ui    /docker-entrypoint.sh            Up (unhealthy)   0.0.0.0:28080->80/tcp,:::28080->80/tcp
ide           /bin/sh -c /usr/src/app/bi ...   Up               0.0.0.0:2081->2081/tcp,:::2081->2081/tcp, 80/tcp
idp           dex serve /dex-setup.yaml        Up               0.0.0.0:5556->5556/tcp,:::5556->5556/tcp,
                                                                0.0.0.0:5558->5558/tcp,:::5558->5558/tcp
mailcatcher   mailcatcher --no-quit --fo ...   Up (healthy)     1025/tcp, 0.0.0.0:1080->1080/tcp,:::1080->1080/tcp`

As you see generic-ui and cafienne are still unhealthy. 
I think that your check for generic UI points to the wrong 'host' (cafienne) 
and the check for cafienne, gives an error with the wget command:
`wget --spider http://localhost:2027/api-docs/swagger.json
Spider mode enabled. Check if remote file exists.
--2021-09-01 14:20:53--  http://localhost:2027/api-docs/swagger.json
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:2027... connected.
HTTP request sent, awaiting response... 405 Method Not Allowed
Remote file does not exist -- broken link!!!`

The above URL works when put into a browser. 
Next to that, there is a /status and a /health endpoint. 
So for the cafienne engine a check like: wget -q http://cafienne:2027/status should be perfect. 

One other request, can you check the consistency with the other docker compose yml files ?

**Comment by tammert** [comment]
@olger I think if you check it again now, you'll get most/all of what you asked for and maybe a little more? :-)
I tested all of these locally and apart from some crashes due to dependencies between `idp` and `generic-ui`, all health checks should be working

**Comment by olger** [comment]
Hi @tammert This looks and works great. Thanks !
I'll merge the whole.

**Pull request merged**
